### ISSUE TITLE
Failed to parse public key error

### ISSUE THREAD

**Issue by jamminjames** [nodesource/nsolid#46] opened 2023-12-11 06:13 UTC
I am getting this error in AlmaLinux 9 OS (RHEL-like), and don’t know what to do about it:
`failed to parse public key for /var/cache/PackageKit/9.2/metadata/nodesource-nsolid-9-x86_64.tmp/NODESOURCE-NSOLID-GPG-SIGNING-KEY-EL`

Nothing is coming up /var/log/nginx/error.log. Since it’s in the cache folder, I tried dnf clean all, didn’t help.

Do I need to remove the package and reinstall, or what? Thanks for any help.

**Comment by santigimeno** [comment] 2023-12-12 13:32
Thanks for reporting. It's an issue with the version of the algorithm the key is using to sign the package. We're aware of this issue and working on a solution. Will keep you posted. Refs:
https://github.com/nodesource/distributions/issues/1653
https://github.com/nodesource/distributions/issues/1693
https://github.com/nodesource/distributions/issues/1721

**Comment by santigimeno** [comment] 2024-01-09 20:15
@jamminjames the issue should be resolved by now. Feel free to reopen if you still have issues.

**Comment by santigimeno** [comment] 2024-01-09 20:20
Sorry, it's still not fixed, it should be in a couple of days. I'll let you know then.

**Comment by JesusPaz** [comment] 2024-01-11 15:36
@jamminjames the issue is fixed. You can run:
```
curl -fsSL https://rpm.nodesource.com/setup_20.x | sudo -E bash -
dnf install nsolid -y
```

or
```
curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo -E bash -
dnf install nsolid -y
```

**Closed as completed by JesusPaz** 2024-01-11 15:36 UTC

**Comment by jamminjames** [comment] 2024-01-11 18:21
Thanks, I ran the first option, and got this:

```
Error: 
 Problem: package nodejs-full-i18n-1:20.9.0-1.module_el9.3.0+48+1cf146a1.x86_64 from @System requires nodejs(x86-64) = 1:20.9.0-1.module_el9.3.0+48+1cf146a1, but none of the providers can be installed
  - cannot install both nodejs-2:20.11.0-1nodesource.x86_64 from nodesource-nodejs and nodejs-1:20.9.0-1.module_el9.3.0+48+1cf146a1.x86_64 from @System
  - cannot install both nodejs-1:20.9.0-1.module_el9.3.0+48+1cf146a1.x86_64 from appstream and nodejs-2:20.11.0-1nodesource.x86_64 from nodesource-nodejs
  - cannot install the best update candidate for package nodejs-full-i18n-1:20.9.0-1.module_el9.3.0+48+1cf146a1.x86_64
  - cannot install the best update candidate for package nodejs-1:20.9.0-1.module_el9.3.0+48+1cf146a1.x86_64
```
However, it then says:
`Repository is configured and updated. Run 'dnf install nodejs -y' to complete the installation.`

But I'm not sure if I should do the install with those errors. Could it be that I should run the second option instead, and if so, do I need to undo the first one somehow?
